spring:
  application:
    name: api-gateway
server:
  port: 8050
eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  #ignored-services: account-service                        # 需要忽视的服务(配置后将不会被路由)
  routes:
    account:                                                            # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /account/**                                                 # 想要映射到的路径
      service-id: account-service     # Eureka中的serviceId
      sensitiveHeaders: "*"
    front-page:
      path: /front-page/**
      service-id: front-page
      sensitiveHeaders: "*"
    test:
      path: /test/**
      service-id: test-service
      sensitiveHeaders: "*"
